### ISSUE TITLE
No Virtual Environment After First Install

### ISSUE THREAD

**Issue by baqwas** [GlassOnTin/picamera2-webstream#1]
The docs state that a virtual environment is created during install. I cannot _see_ one after an installation with no error message.

**Comment by GlassOnTin** [comment]
I've now updated the `install_picamera.sh` and `install_ffmpeg.sh` to make it clear where the venv is created.

**Comment by baqwas** [comment]
Thanks again. Just for the record, I tripped up on "**yourusername**" because I didn't pay attention in my headlong rush to install. Not an issue, of course.

Regards.
